### ISSUE TITLE
error when using ets with time series of 24 elements

### ISSUE THREAD

**Issue by emriva** [robjhyndman/forecast#115] opened 2015-05-18 15:58 UTC
When I use ets function with a time series of 24 elements I got an error: "error in Fourier (x,k,1:lenght(x))
k must be not be Greater than period/2".
Why I get this problem and how to fix it?
thanks
ER

**Comment by robjhyndman** [comment] 2015-05-18 23:38
I cannot reproduce this error. Please provide a reproducible example.

**Comment by emriva** [comment] 2015-05-19 07:37
Dear Dr. Hyndman,

 

thanks for the quick reply.

 

I’m using R software version 3.2 (64 bit) with Win 8.1

The forecast library version is 6.1

 

I attach the program and the input file.

The error is the following



 

AS you can see the error happens only when I want to introduce the seasonality in the model.

 

If I reduce the periods from 24 to 12 or if I add 12 months in the input file the ets function works.

 

I hope this is enough for you to reproduce the problem.

 

Kind regards

 

Enrico Riva

 

 

Da: Rob J Hyndman [mailto:notifications@github.com] 
Inviato: martedì 19 maggio 2015 01:38
A: robjhyndman/forecast
Cc: emriva
Oggetto: Re: [forecast] error when using ets with time series of 24 elements (#115)

 

I cannot reproduce this error. Please provide a reproducible example.

**Comment by robjhyndman** [comment] 2015-05-19 07:51
Nothing appears to be attached. Do not attach by email.

**Comment by emriva** [comment] 2015-05-19 08:19
input file:
SwordDemand
165
171
147
143
164
160
152
150
159
169
173
203
169
166
162
147
188
161
162
169
185
188
200
229

Program file:
library(forecast)
sword <-read.csv("D:/Lavoro/DATA/Books/Wiley Datasmart/Ch 10 - SwordDemand.csv")
sword.ts <- ts(sword,frequency=12,start=c(2005,1))
sword.forecast <- forecast(sword.ts)
plot(sword.forecast)
![cattura](https://cloud.githubusercontent.com/assets/12499158/7698423/74290356-fe10-11e4-95cd-8ae4e6c88400.PNG)

**Comment by robjhyndman** [comment] 2015-05-19 09:31
I still cannot reproduce the problem. Make sure you have updated to the latest version of the software and try again.

**Comment by emriva** [comment] 2015-05-25 14:35
I installed the lastest R software (3.2.0) and the latest forecast library (6.1) in a brand new computer but when I forecast a time series of 24 elements with frequency = 12 I stil get the same error "Error in ...fourier(x, K, 1:length(x)) : 
  K must be not be greater than period/2".
if the elements are 12 or 36 (Always with frequency = 12), everything is fine.. 
I don't understand what is wrong.
ERiva

**Comment by robjhyndman** [comment] 2015-05-25 21:54
This is not reproducible:
```
> sword <- c(165,171,147,143,164,160,152,150,159,169,173,203,169,166,162,147,
+ 188,161,162,169,185,188,200,229)
> sword.ts <- ts(sword,frequency=12,start=c(2005,1))
> forecast(sword.ts, h=3)
         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
Jan 2007       214.1648 187.1237 241.2059 172.8090 255.5206
Feb 2007       214.1648 182.7921 245.5375 166.1843 262.1453
Mar 2007       214.1648 178.9779 249.3517 160.3511 267.9785
```

Try restarting your R session with a clean workspace. It is possible your own functions are causing the problem. In particular, remove any function called "fourier".

**Comment by emriva** [comment] 2015-05-30 18:10
I found the problem:
the problem occurs when the function forecast is used in combination with:
* a vector (sword in our example) that is fulfilled from a text file .csv using the function read.csv AND
* the number of elements is 24.

Actually if you:
* fulfil the vector with the function c(..,..,..) OR
* the number of elements is different that 24
the problem doesn't occur.

I used a different function that read.csv to fulfil the vector (for example, I used a function that read an Excel file) AND I GOT THE SAME ERROR with the same configuration (that means the error appears only when the historical time series is of 24 elements).

I hope now you can replicate the error.

**Comment by robjhyndman** [comment] 2015-05-31 00:34
Thanks. Now fixed in https://github.com/robjhyndman/forecast/commit/d76c322ceeea85d71fe76466c4cc56d626513eeb

**Closed by robjhyndman** 2015-05-31 00:34 UTC
