### ISSUE TITLE
weights not working in tslm

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#387] opened 2016-11-10 22:39 UTC
See http://stackoverflow.com/q/40528668/144157

**Comment by mitchelloharawild** [comment] 2016-11-11 06:40
Weird! Fixed in #388.

An abstraction of the issue is below:
```R
lmWrap <- function(formula, ...){
  return(lm(formula, ...))
}
trend <- 1:36
lmWrap(rnorm(36)~trend, weights = 0.9^(1:36))
```
 Error in eval(expr, envir, enclos) : 
  ..1 used in an incorrect context, no ... to look in 

What made it work in forecast 7.1 was my usage of reformulate() to change the formula names... which miraculously made this work. I suppose the evaluation environment somewhere deep in lm() is taken from the environment of the formula, which is changed to make `...` work when using reformulate().

```R
lmWrap2 <- function(formula, ...){
  mt <- terms(formula)
  vars <- attr(mt, "variables")
  formula <- stats::reformulate(attr(mt, "term.labels"), response = vars[[attr(mt, 
                                                                               "response") + 1]], intercept = attr(mt, "intercept"))
  return(lm(formula, ...))
}
```

**Closed** 2016-11-11 07:10 UTC
