### ISSUE TITLE
nnetar for some series gives error "Error in predict.nnet(X[[i]], ...) : missing values in 'x'"

### ISSUE THREAD

**Issue by SinghB** [robjhyndman/forecast#340] opened 2016-06-23 16:16 UTC
Seems to be happening because of missing na.rm = TRUE in some places where means are being calculated.
Also happens if I use repeats = 1

**Comment by robjhyndman** [comment] 2016-06-24 08:44
This works:
```
gold[sample(1108,20)] <- NA
fit <- nnetar(gold)
forecast(fit)
```

Please provide a minimal reproducible example of the problem.

**Comment by nidabdella** [comment] 2016-06-24 13:08
Hi, Here is an example where I reproduced the error (I might be using the function the wrong way that's why I get this erroe): 
```
consumption = c(69,55,30,40,42,42,15,20,34,20,82,35,45,49,35,5,58,75,15,35,20,40,10,30)
dates = as.Date(as.character(c("2011-08-17", "2011-08-18", "2011-08-19", "2011-08-20", "2011-08-22", "2011-08-23", "2011-08-24", "2011-08-25", "2011-08-26", "2011-08-27","2011-08-30", "2011-08-31", "2011-09-01", "2011-09-03", "2011-09-05", "2011-09-07", "2011-09-08", "2011-09-09", "2011-09-12", "2011-09-13","2011-09-14", "2011-09-17", "2011-09-19", "2011-09-20")), '%Y-%m-%d')

ts = cbind(dates, consumption) 
ts
tsxts = xts(consumption, order.by = as.POSIXct(dates))
plot(tsxts)

neuraldf = nnetar(tsxts, p = 3) 
ncast = forecast(neuraldf,h=10)
```

**Comment by gabrielcaceres** [comment] 2016-06-24 16:16
I'm also not able to reproduce the error. The only way means and standard deviations of the data are calculated is through `scale` which omits NAs by default. 

The one exception where I am able to reproduce the error, is if there are missing values at the tail end of the series which are needed for the forecast:
```
gold[length(gold)-1] <- NA
fit <- nnetar(gold, p=3)
forecast(fit)
# > Error in predict.nnet(X[[i]], ...) (from nnetar.R#259) : missing values in 'x'
```
In that situation forecasts obviously cannot be done due to the missing values, and currently the code does not try to address that since it's not as simple as just omitting them (as is done if there are NAs elsewhere in the series).

Perhaps we could add a more explicit error for when this occurs. 

@nidabdella the error you encountered is a bit strange in that even after setting the random seed, I was only able to reproduce it sporadically. Regardless, I think it stems from the fact that `nnetar` requires a `ts` object, not `xts`. When giving a non-`ts` object, it will be coerced into one. In the example you gave, this gives it a non-integer frequency value which is probably tripping something up in an unexpected way.

```
consumption = c(69,55,30,40,42,42,15,20,34,20,82,35,45,49,35,5,58,75,15,35,20,40,10,30)
dates = as.Date(as.character(c("2011-08-17", "2011-08-18", "2011-08-19", "2011-08-20", "2011-08-22", "2011-08-23", "2011-08-24", "2011-08-25", "2011-08-26", "2011-08-27","2011-08-30", "2011-08-31", "2011-09-01", "2011-09-03", "2011-09-05", "2011-09-07", "2011-09-08", "2011-09-09", "2011-09-12", "2011-09-13","2011-09-14", "2011-09-17", "2011-09-19", "2011-09-20")), '%Y-%m-%d')

tsxts = xts(consumption, order.by = as.POSIXct(dates))

as.ts(tsxts)
# Time Series:
# Start = 1 
# End = 1987201 
# Frequency = 1.15740740740741e-05 
#  [1] 69 55 30 40 42 42 15 20 34 20 82 35 45 49 35  5 58 75 15 35 20 40 10 30
```

**Comment by robjhyndman** [comment] 2016-09-07 04:19
Problems now fixed in https://github.com/robjhyndman/forecast/commit/2caec4016176cb79bce2d94004c5ad2dd3a59393 and https://github.com/robjhyndman/forecast/commit/b31c4812859c52308ae9bad6939cb28d1e390b18

**Closed by robjhyndman** 2016-09-07 04:19 UTC

**Comment by andirey** [comment] 2019-11-29 19:49
Dear Rob!
I used today function "nnetar" and it gives me an error when there are NAs values.
I simply drop these values, but it seems "nnetar" could be improved by taking into account this moment. Thanks, Andrii

**Comment by robjhyndman** [comment] 2019-11-30 00:57
Please provide a reproducible example. And make sure you are using the latest CRAN version of the package.

**Comment by mlduarte** [comment] 2020-04-01 22:25
Hi Rob - here is some code 

```
dummy <- as.numeric(calls)[1:1186]
dummy[c(93, 104, 359, 454, 724, 839, 1089)] <- NA
dummy <- msts(dummy, start = c(0, 1), seasonal.periods=c(7,366))
fit <- nnetar(dummy, lambda=0)
pred <- forecast(fit, h = 61)
```

Error in forecast.nnetar(fit, h = 61) : 
  I can't forecast when there are missing values near the end of the series.


Extract of session info: other attached packages:
[1] fpp2_2.3      expsmooth_2.3 fma_2.4       ggplot2_3.2.1 forecast_8.10

**Comment by robjhyndman** [comment] 2020-04-01 23:00
The problem is that there is a missing value in the last year, and the NNAR model is using a lag of 366. Forecasting with h up to 18 is fine because the missing value is not used as an input. But forecast for h >= 19 causes problems. Interpolating fixes the problem, but you have to be sure that a good estimate is used in place of the missing value.

The error message makes this clear I think.

**Comment by mlduarte** [comment] 2020-04-01 23:09
Yes, error message is clear.  Thought this may have been what @andirey  encountered.
