### ISSUE TITLE
`auto.arima` flags valid model as `Inf`

### ISSUE THREAD

**Issue by landroni** [robjhyndman/forecast#629] opened 2017-12-11 08:15 UTC
I am using `forecast 7.2` and trying to figure the best ARIMA specification for a set of monthly data and for some reason `auto.arima` flags a valid model as `Inf`. The model in question is the model I would have selected given the ACF and PACF graphs (i.e. `ARIMA(0,1,1)(3,1,1)[12]`), and intriguingly the best model according to goodness of fit measures. 

`Arima` has no problems fitting this specification, but `auto.arima` will flag it as `Inf`: 
```
auto.arima(x.ts, lambda=0, 
                      d=1, D=1, max.order=9, max.P = 3,
                      stepwise = FALSE, approximation = FALSE, trace = TRUE, 
                      parallel = TRUE, num.cores = 3)
[...]
ARIMA(0,1,1)(3,1,0)[12]				:	268.538
ARIMA(0,1,1)(3,1,1)[12]				:	Inf
```

This is strange because the fit looks good to me: 
```
> Arima(x.ts, order=c(0,1,1), seasonal = c(3,1,1), lambda = 0)  ##graphs

Series: x.ts 

ARIMA(0,1,1)(3,1,1)[12]                    

Box Cox transformation: lambda= 0

[..] 

sigma^2 estimated as 0.1435:  log likelihood=-113.82

AIC=239.63   AICc=240.02   BIC=260.13
```

`auto.arima`'s preferred version doesn't seem to be as good a fit: 
```
> Arima(x.ts, order=c(0,1,1), seasonal = c(3,1,0), lambda = 0)  ##aa1

Series: x.ts 

ARIMA(0,1,1)(3,1,0)[12]                    

Box Cox transformation: lambda= 0

[...] 

sigma^2 estimated as 0.181:  log likelihood=-129.13

AIC=268.26   AICc=268.54   BIC=285.34
```

Is it expected that the `ARIMA(0,1,1)(3,1,1)[12]` would be flagged as `Inf`? I looked at the JSS paper, the book and the docs, and it isn't entirely obvious to me how the algorithm decides to discard a given model.

**Comment by robjhyndman** [comment] 2017-12-11 08:50
First, you are using a version that is over one year old. Please update your packages.

Your issue is not reproducible because you did not provide data. But most likely the characteristic roots of the model are close to the unit circle. The algorithms avoids such models because they are numerically unstable.

**Comment by landroni** [comment] 2017-12-12 07:21
Yes, unfortunately the data is private and not something that I could share, but I would gladly run any diagnostics or debugging that could help figure out what's going on. (I'm now waiting for IT to update the package.) 

> But most likely the characteristic roots of the model are close to the unit circle. 

I'm wondering why this would be the case. Best I can see unit roots are used in determining `d` and `D`. But in this specific case both differencing parameters were fixed from the outset to `d=1, D=1`, for both models. So I'm not sure why one would fail unit root tests but the other would not.

**Comment by robjhyndman** [comment] 2017-12-12 07:28
The AR and MA terms have roots. They could be close to the unit circle. As you cannot provide a reproducible example, I am closing this issue.

**Closed by robjhyndman** 2017-12-12 07:28 UTC

**Comment by landroni** [comment] 2017-12-12 14:31
What function could I use to test whether the roots for the AR or MA terms are close to the unit circle?

**Comment by landroni** [comment] 2017-12-13 04:08
Missed that part. Thanks!
