### ISSUE TITLE
Differences in information criteria values

### ISSUE THREAD

**Issue by config-i1** [robjhyndman/forecast#405] opened 2016-12-01 23:32 UTC
Not sure if this is a bug or a feature...

> test <- ets(c(1:10,7,1,3))
>AIC(test)

The model returns AIC = 54.54895, while the method returns 52.54895. Is AIC not taking all the degrees of freedom into account (variance missing probably)?

**Comment by robjhyndman** [comment] 2016-12-01 23:35
It is a bug in the stats::AIC.default function. Perhaps I should write my own AIC.xxx methods to prevent this happening.

**Comment by config-i1** [comment] 2016-12-01 23:38
Is it because of logLik function? It returns in that case:
> 'log Lik.' -24.27447 (df=2)
I thought that may be df=2 is wrong, because variance is not taken into account...
When I calculate manually with df=3, I get the value from ets model.

**Comment by robjhyndman** [comment] 2016-12-01 23:39
Yes, the df=2 is wrong. And yes, it is because of the variance parameter. I've opened an issue here: https://github.com/robjhyndman/forecast/issues/406

**Comment by robjhyndman** [comment] 2016-12-01 23:40
Ah. I just realised that the problem is actually forecast::logLik.ets. Damn. Will fix it.

**Comment by config-i1** [comment] 2016-12-01 23:42
Cheers!

And by the way I have recently found out that BIC method from stats will work if you introduce nobs.ets function in the package. Not sure if this is needed in forecast at all but maybe useful :)

**Comment by robjhyndman** [comment] 2016-12-01 23:45
loglik function fixed in https://github.com/robjhyndman/forecast/commit/a10ab626aeedc94a165e5d77e4e338500b756c58

**Comment by robjhyndman** [comment] 2016-12-01 23:49
nobs.ets added in https://github.com/robjhyndman/forecast/commit/fd5330351f9eb3a11a24636377b6ca97b9e15f2d

**Comment by robjhyndman** [comment] 2016-12-01 23:49
Thanks for the bug notification and the suggestion!

**Closed by robjhyndman** 2016-12-01 23:49 UTC
