### ISSUE TITLE
xreg with do.call (auto.arima) - unexpected behavior

### ISSUE THREAD

**Issue by JohnForecastR** [robjhyndman/forecast#780] opened 2019-02-27 21:06 UTC
I am using auto.arima with xreg and do.call, as follows: 
```r
foo<-function(vec_ts,...){

  args = list(...)
  args$y<-vec_ts # time series vector

  fit<-do.call(auto.arima,args)

}
```
`...` may or may not include `xreg`. In case it includes, I have realized that for some time series it works well, but for some others it produces the following error which I couldn't solve: 

**Error in dimnames(x) <- dn : length of 'dimnames' [2] not equal to array extent**

Here is a reproducible case:

```r
# create argument list
args=list()
args$y<-ts(c(100:140,rep(200,4),380,250),start=c(2016,1),frequency = 52)
args$seasonal<-F
args$xreg<-(diag(length(args$y))%>%.[,-c(1:24)])

# this works well
fit1<-auto.arima(y=args$y,seasonal=args$seasonal,xreg=args$xreg)

# but this does NOT work, although everything is the same!
fit2<-do.call(auto.arima,args)

# however, if we change arguments slightly, do.call works well, as seen below:
args$y<-ts(10:20,start=c(2016,1),frequency = 52)
args$xreg<-(diag(length(args$y))%>%.[,-c(1:4)])

fit2<-do.call(auto.arima,args)
```

**Comment by mitchelloharawild** [comment] 2019-02-28 03:57
I am unable to reproduce this with the development version of the package. Please try updating the package and try again.

``` r
library(forecast)

# create argument list
args=list()
args$y<-ts(c(100:140,rep(200,4),380,250),start=c(2016,1),frequency = 52)
args$seasonal<-F
args$xreg<-(diag(length(args$y))%>%.[,-c(1:24)])

# this works well
fit1<-auto.arima(y=args$y,seasonal=args$seasonal,xreg=args$xreg)

# but this does NOT work, although everything is the same!
fit2<-do.call(auto.arima,args)

print(fit1)
#> Series: args$y 
#> Regression with ARIMA(0,0,0) errors 
#> 
#> Coefficients:
#>       intercept    xreg1    xreg2    xreg3    xreg4    xreg5    xreg6
#>        111.5000  12.5000  13.5000  14.5000  15.5000  16.5000  17.5000
#> s.e.     1.0097   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>         xreg7    xreg8    xreg9   xreg10   xreg11   xreg12   xreg13
#>       18.5000  19.5000  20.5000  21.5000  22.5000  23.5000  24.5000
#> s.e.   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>        xreg14   xreg15   xreg16   xreg17   xreg18   xreg19   xreg20
#>       25.5000  26.5000  27.5000  28.5000  88.5000  88.5000  88.5000
#> s.e.   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>        xreg21    xreg22    xreg23
#>       88.5000  268.5000  138.5000
#> s.e.   5.0485    5.0485    5.0485
#> 
#> sigma^2 estimated as 50:  log likelihood=-141.83
#> AIC=333.66   AICc=395.56   BIC=379.91
print(fit2)
#> Series: structure(c(100, 101, 102, 103, 104, 105, 106, 107, 108, 109,  110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,  123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,  136, 137, 138, 139, 140, 200, 200, 200, 200, 380, 250), .Tsp = c(2016,  2016.88461538462, 52), class = "ts") 
#> Regression with ARIMA(0,0,0) errors 
#> 
#> Coefficients:
#>       intercept    xreg1    xreg2    xreg3    xreg4    xreg5    xreg6
#>        111.5000  12.5000  13.5000  14.5000  15.5000  16.5000  17.5000
#> s.e.     1.0097   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>         xreg7    xreg8    xreg9   xreg10   xreg11   xreg12   xreg13
#>       18.5000  19.5000  20.5000  21.5000  22.5000  23.5000  24.5000
#> s.e.   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>        xreg14   xreg15   xreg16   xreg17   xreg18   xreg19   xreg20
#>       25.5000  26.5000  27.5000  28.5000  88.5000  88.5000  88.5000
#> s.e.   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485   5.0485
#>        xreg21    xreg22    xreg23
#>       88.5000  268.5000  138.5000
#> s.e.   5.0485    5.0485    5.0485
#> 
#> sigma^2 estimated as 50:  log likelihood=-141.83
#> AIC=333.66   AICc=395.56   BIC=379.91
identical(coef(fit1), coef(fit2))
#> [1] TRUE

# however, if we change arguments slightly, do.call works well, as seen below:
args$y<-ts(10:20,start=c(2016,1),frequency = 52)
args$xreg<-(diag(length(args$y))%>%.[,-c(1:4)])

fit2<-do.call(auto.arima,args)
print(fit2)
#> Series: structure(10:20, .Tsp = c(2016, 2016.19230769231, 52), class = "ts") 
#> Regression with ARIMA(0,0,0) errors 
#> 
#> Coefficients:
#>         xreg1    xreg2    xreg3    xreg4    xreg5    xreg6    xreg7
#>       14.0000  15.0000  16.0000  17.0000  18.0000  19.0000  20.0000
#> s.e.   6.9675   6.9675   6.9675   6.9675   6.9675   6.9675   6.9675
#> 
#> sigma^2 estimated as 133.5:  log likelihood=-36.96
#> AIC=89.92   AICc=161.92   BIC=93.11
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment] 2019-08-19 04:11
Closing as I'm unable to reproduce this issue and no MRE has been provided.

**Closed by mitchelloharawild** 2019-08-19 04:11 UTC
Labels: Awaiting MRE
